Make site more mobile responsive
astei/crafthead pull request #51
Opened 2022-03-22 00:42 UTC by bribes

2022-03-22 01:09 UTC, TibiNonEst approved these changes

2022-03-27 02:08 UTC, astei requested changes

2022-03-27 02:08 UTC, astei commented on website/index.css
> +  width: 154;
What unit?

2022-03-27 02:08 UTC, astei commented on website/index.css
> +        width: 300;
ditto

2022-03-27 02:57 UTC, astei approved these changes
I'll deploy this tomorrow

2022-03-27 02:57 UTC, merged